# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a22d4d11472aaafe9762b0d3293dfa51789008cd6766db7928fd764770ec0c2ac8af5a1c63c51cc2ef880d108d838f8e0f6fc23e9dc5f3dda2c622a0ab74cda5

test:
  secret_key_base: a2b865d3b4f78193896f759067ec37cb3dfa3f4c72eeb06ece1b07c0d5182bdffa6691c8e8ab56fad46bc1104996f3596644e0ec5dc7eb1f31cf2c85b609dc61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
